# Generated by Django 3.2.2 on 2021-06-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='authors',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='pmid',
            field=models.CharField(max_length=555, unique=True),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='title',
            field=models.CharField(max_length=555),
        ),
    ]
