# Generated by Django 3.2.2 on 2021-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0002_auto_20210613_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='keywords',
            field=models.CharField(max_length=555),
        ),
    ]
