# Generated by Django 3.2.2 on 2021-05-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0002_auto_20210512_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
