# Generated by Django 3.2.2 on 2021-06-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
