# Generated by Django 3.2.2 on 2021-05-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0002_auto_20210514_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='user',
        ),
    ]
