# Generated by Django 3.2.2 on 2021-06-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0003_alter_tagmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagmodel',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
