# Generated by Django 3.2.2 on 2021-05-12 12:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0003_alter_articlemodel_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
