# Generated by Django 3.2.2 on 2021-05-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0004_alter_articlemodel_publish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='pmid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
