# Generated by Django 3.2.2 on 2021-06-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0004_auto_20210613_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='authors',
            field=models.CharField(max_length=1000),
        ),
    ]
