# Generated by Django 3.2.2 on 2021-06-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0005_alter_articlemodel_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='authors',
            field=models.CharField(max_length=10000),
        ),
    ]
