# Generated by Django 3.2.2 on 2021-06-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0006_alter_articlemodel_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
