# Generated by Django 3.2.2 on 2021-05-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SWE573_Project', '0006_reportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='SWE573_Project.articlemodel'),
        ),
    ]
